services:
    web:
        environment:
            - EXTENSION_KEY=fal_s3
            - PACKAGE_NAME=maxserv/fal_s3

            # TYPO3 v14 config
            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_USER=root
            - TYPO3_INSTALL_DB_PASSWORD=root
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=0
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=Password:joh316
            - TYPO3_INSTALL_SITE_NAME=EXT:fal_s3 Dev Environment
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/fal_s3
              consistency: cached
            - v14-data:/var/www/html/v14
volumes:
    v14-data:
        name: "${DDEV_SITENAME}-v14-data"
